/* No Excuses — achievements (build 16, refactor stage 2). DATA ONLY (A2).
   Per game, three tiers plus secrets. `unlocks` is [customise group, value]; `at` is where tapping the row takes you;
   `hint` is the description a SECRET row shows in place of its name (v14 8.5) — it says what kind of thing earns it, never the number.
   (`s:-1` is the Streak length). The predicate (ACH_TEST) and the 0..1 progress bar (ACH_PROGRESS) live in
   progress/rules.js under the same id.

   `live:1` (build 23, v15 §2.5) is the same flag UNLOCKS carries and it means the same thing: this row's test can only
   become MORE true as a run goes on, so it is checked on every live tick and banked to the store the moment it fires —
   a player who quits mid-run keeps it. Rows without it are totals, averages or "no wrong taps" claims about a WHOLE run,
   which a partial run cannot honestly satisfy; those still wait for the finish. Every earn is written the instant it
   happens either way: run/run.js now banks at finish before the ad break, not after it.

   v17 (B.6, build 28): NINE rows lost `live:1` — every "clean run" row (qt_clean5, qt_bclean5, qt_clean15, qt_clean30,
   qt_eyes, dt_pin, dt_bpin, dt_land) and Committed (qt_sab). Each tests `misses===0` or `hits===0` about the WHOLE run,
   and both can go FALSE on the next tap, so the flag was banking them from a partial run that had not earned them.

   v24 (D.2, build 44, narrowing #435): THE PER-MODE ROWS ARE THE KEY ROSTER NOW. One achievement sits on every key requirement
   at every tier — 30 combinations in config/key-bars.js × 3 = 90 rows — generated by progress/key.js keyAch() and named in
   KEY_ROSTER below. Twenty-three rows that used to live in ACH are among them: each keeps its id (so a profile that earned it
   keeps it, and a cosmetic it opened stays open — config/theme.js `by` still names it) and its reward, and is earned from now on
   by clearing that combination's bar at its tier. What is left in ACH is Everywhere, Secret, and the rows that never were a
   one-per-mode key row (Desk v5.2's "Customise only" group). Neither feeds a key. */
export const ACH = [
  // everywhere
  { id:'first',   g:'all', tier:'earned', name:'Showed up',   how:'Finish any run', unlocks:['sq','#FFE9C4'] },
  { id:'named',   g:'all', tier:'earned', name:'Signed in',   how:'Put a name on your profile, top of the Scores screen', unlocks:['bg','grid'] },
  { id:'every',   g:'all', tier:'earned', name:'Every game',  how:'Finish a run in every game', unlocks:['lead','#FFB020'] },
  { id:'fullset', g:'all', tier:'pro',    name:'Full set',    how:'In one game, every mode at every length', unlocks:['wheel'] },
  // v8: the first "big" unlock — a sound pack that is mostly a joke
  { id:'tour',    g:'all', tier:'pro',    name:'Grand tour',  how:'Finish a run in every mode of every game', unlocks:['snd','sigh'] },
  // v11: the easter egg. Three taps on the full stop under the top 10. Never earned by a run
  { id:'egg',     g:'all', tier:'secret', name:'Excuses',     how:'Found the full stop', hint:"Not something you can play for. Something on the result screen is punctuation and something is not.", unlocks:['sq','#FF7A59'] },
  // quick tap — every one is Two or Four, never "any mode" (v6)
  { id:'qt_r4',      g:'quick-tap', tier:'earned', name:'Quick',                how:'Four · 3 hits a second, any length', unlocks:['snd','click'], at:{d:'four'}, live:1 },
  { id:'qt_clean15', g:'quick-tap', tier:'earned', name:'Clean · Dash',         how:'Four · Dash, no misses, at least 24 hits', unlocks:['bg','rain'], at:{d:'four',s:15} },
  { id:'qt_clean30', g:'quick-tap', tier:'pro',    name:'Clean · Marathon',     how:'Four · Marathon, no misses, at least 50 hits', unlocks:['sq','#C6FF7A'], at:{d:'four',s:30} },
  { id:'qt_eyes',    g:'quick-tap', tier:'pro',    name:'Eyes shut',            how:'Two · clean Marathon, at least 60 hits', unlocks:['lead','#FF4FD8'], at:{d:'two',s:30} },
  { id:'qt_sab',     g:'quick-tap', tier:'pro',    name:'Committed',            how:'Two · a run of nothing but misses, at least five', at:{d:'two'} },
  { id:'qt_s5',      g:'quick-tap', tier:'secret', name:'No excuses',           how:'Four · 5 hits a second on a Sprint', hint:"Four pads, the shortest length, and a rate no Pro row asks for.", at:{d:'four',s:5}, live:1 },
  { id:'qt_s15',     g:'quick-tap', tier:'secret', name:'Still no excuses',     how:'Four · 5 hits a second, held for a Dash', hint:"That same rate, held for a whole Dash.", at:{d:'four',s:15}, live:1 },
  { id:'qt_s30',     g:'quick-tap', tier:'secret', name:'Not normal',           how:'Four · 5 hits a second, held for a Marathon', hint:"That same rate again, held for a whole Marathon.", at:{d:'four',s:30}, live:1 },
  { id:'qt_bs5',     g:'quick-tap', tier:'secret', name:'Two faith',            how:'Two · 5 hits a second on a Sprint', hint:"Two pads, a Sprint, and a rate that belongs on Four.", at:{d:'two',s:5}, live:1 },
  // dots
  { id:'dt_sweep', g:'dots', tier:'earned', name:'Sweep',            how:'Lead · 3 hits a second over a Dash', unlocks:['lead','#7CFFB2'], at:{d:'lead',s:15}, live:1 },
  { id:'dt_s',     g:'dots', tier:'secret', name:'Radar',            how:'Lead · 4.5 a second held for a Marathon', hint:"Lead, a Marathon, faster than every Pro row on the board.", at:{d:'lead',s:30}, live:1 },
  { id:'dt_bs',    g:'dots', tier:'secret', name:'Sonar',            how:'Blind · 3.5 a second held for a Marathon', hint:"The same, Blind — with no ring showing you where next.", at:{d:'blind',s:30}, live:1 },
  // hold (v11: a Set scores the average % off across 7 rounds — lower is better; a Streak scores rounds)
  { id:'hd_run',    g:'hold', tier:'pro',    name:'Long haul',    how:'A Streak of 15 rounds, either mode', at:{s:-1}, live:1 },
  { id:'hd_s',      g:'hold', tier:'secret', name:'Machine',      how:'Every round of a Set within 4.00%', hint:"Not the average. Every single round of a Set inside a very small margin.", at:{s:7} },
  // v15 (1.5): the deliberate-fail joke, Estimate's answer to Quick Tap's "Committed". Secret, because Aiden's secret tier
  // is explicitly the deliberate fails and the hidden finds (#350) — a Pro row would put it in a list of things to aim at
  { id:'hd_max',    g:'hold', tier:'secret', name:'Greedy',       how:'Grow · let the shape run all the way to its limit', hint:"Accuracy has nothing to do with this one. You were shown a size. Ask for very much more than that, and do not let go.", at:{d:'grow'}, live:1 },
  // sequence
  { id:'sq_7x8',  g:'sequence', tier:'pro',    name:'Wide open',    how:'Round 8 on seven keys', at:{s:7}, live:1 },
  // v17 (B.9): was 'Ten on five'. Five keys is gone, so the row was moved to three keys (guess)
  { id:'sq_5x10', g:'sequence', tier:'pro',    name:'Ten on three', how:'Round 10 on three keys', at:{s:3}, live:1 },
  { id:'sq_s20',  g:'sequence', tier:'secret', name:'Twenty',       how:'Round 20 on any keys', hint:"Twice as far as the Pro row goes. Say them out loud.", live:1 },
  { id:'sq_s15',  g:'sequence', tier:'secret', name:'The long one', how:'Round 15 on seven keys', hint:"The long one, on the widest board.", at:{s:7}, live:1 },
  // v18 (B.2): the Set is a total, so the same standard is 0.12s a round across five — 0.60s, not a new number
  { id:'tm_s',     g:'timing',   tier:'secret', name:'Metronome',     how:'Stopwatch · a Set under 0.60s off in total', hint:"A whole Set closer, round for round, than the Pro row asks for one attempt.", at:{d:'stopwatch',s:5} },
  /* v17 (B.12): let one Stopwatch attempt run the full CFG.swOver seconds past its target instead of tapping. NAME IS A
     PLACEHOLDER: Aiden names the secret rows himself. `live:1` is honest — `ov` is set the moment the clock runs out. */
  { id:'tm_s10',   g:'timing',   tier:'secret', name:'The long wait', how:'Stopwatch · let one attempt run the full 10 seconds past its target', hint:"Nothing to do with accuracy. There is a point at which the game gives up waiting for you. Find it.", at:{d:'stopwatch'}, live:1 },
  { id:'rx_s',     g:'reaction', tier:'secret', name:'Twitch',        how:'Flash · a Set averaging under 180ms', hint:"A Set average under what most people manage once.", at:{d:'flash',s:5} },
];
/* v18 (B.24 / B.25, build 32): AUTHOR_RECORDS is RETIRED. The Author KEY is that idea done properly: the `author` column of
   config/key-bars.js (B.27) is where his times live, the radar's third rung reads it (B.24) and the Author rows are generated
   from it. A.5 still holds for that column: captured once, then frozen. */

/* v24 (D.2, build 44): THE NAMES OF THE 90 KEY ROWS, keyed by the combination's id in config/key-bars.js, one entry per tier —
   `clear` is key 1. Read off the Key Unlocks Desk page on 2026-09-15 (FEEDBACK-v24 §D.3). An entry with an `id` REPLACES the
   older achievement of that id — it keeps the id and its `unlocks` — and an entry without one is new, its id generated as
   key_<tier>_<combination id>. Aiden retypes names on the desk; a rename is an edit here and nowhere else. */
export const KEY_ROSTER = {
  'qt-two-5':       { clear:{ id:'qt_bclean5', name:'Two hands' },                                  pro:{ name:'Warm start' },                                    author:{ name:'Two flat out' } },
  'qt-two-15':      { clear:{ name:'Two steady' },                                                  pro:{ id:'qt_br4', name:'Two quick' },                        author:{ name:'Two better' } },
  'qt-two-30':      { clear:{ name:'Two long' },                                                    pro:{ name:'Two lasting' },                                   author:{ name:'Two unbeaten' } },
  'qt-four-5':      { clear:{ id:'qt_clean5', name:'Warm hands', unlocks:['sq','#9BE8FF'] },        pro:{ name:'Off the mark' },                                  author:{ name:'Out of the gate' } },
  'qt-four-15':     { clear:{ name:'Finding it' },                                                  pro:{ id:'qt_r5', name:'Quicker', unlocks:['lead','#4FD9FF'] }, author:{ name:'Out-tapped' } },
  'qt-four-30':     { clear:{ name:'Still going' },                                                 pro:{ name:'Relentless' },                                    author:{ name:'Unmatched' } },
  'dt-blind-5':     { clear:{ id:'dt_bpin', name:'Blind luck' },                                    pro:{ name:'Blind start' },                                   author:{ name:'Blind best' } },
  'dt-blind-15':    { clear:{ name:'Feeling it' },                                                  pro:{ id:'dt_blind', name:'Homing' },                         author:{ name:'Second sight' } },
  'dt-blind-30':    { clear:{ name:'Blind faith' },                                                 pro:{ name:'Dead reckoning' },                                author:{ name:'Sixth sense' } },
  'dt-lead-5':      { clear:{ id:'dt_pin', name:'Pinpoint', unlocks:['sq','#FFD1DC'] },             pro:{ name:'Quick eye' },                                     author:{ name:'First strike' } },
  'dt-lead-15':     { clear:{ name:'Tracking' },                                                    pro:{ name:'On the tail' },                                   author:{ name:'Locked on' } },
  'dt-lead-30':     { clear:{ name:'Long chase' },                                                  pro:{ id:'dt_land', name:'Landing', unlocks:['bg','orbs'] },  author:{ name:'Sharper' } },
  'es-grow-set':    { clear:{ id:'hd_steady', name:'Steady hand', unlocks:['sq','#F3D9FF'] },       pro:{ name:'Green thumb' },                                   author:{ name:'Outgrown' } },
  'es-grow-streak': { clear:{ name:'Keeps growing' },                                               pro:{ name:'Runs on' },                                       author:{ name:'Never stops' } },
  'es-cut-set':     { clear:{ id:'hd_money', name:'On the money', unlocks:['snd','wood'] },         pro:{ id:'hd_est', name:'Good eye', unlocks:['lead','#FFFFFF'] }, author:{ name:'Cleaner cut' } },
  'es-cut-streak':  { clear:{ name:'Keeps cutting' },                                               pro:{ name:'Long division' },                                 author:{ name:'Endless edge' } },
  'sq-3':           { clear:{ id:'sq_7', name:'Seven', unlocks:['bg','stars'] },                    pro:{ id:'sq_12', name:'Twelve', unlocks:['sq','#FFF3A0'] },  author:{ name:'Longer memory' } },
  'sq-7':           { clear:{ name:'Wide open' },                                                   pro:{ name:'Seven wide' },                                    author:{ name:'Total recall' } },
  'tm-sw-set':      { clear:{ id:'tm_close', name:'Dead on' },                                      pro:{ name:'Fine margin' },                                   author:{ name:'Better clock' } },
  'tm-sw-streak':   { clear:{ name:'Still counting' },                                              pro:{ id:'tm_run', name:'Keeps going' },                      author:{ name:'Never off' } },
  'tm-hid-set':     { clear:{ name:'In the dark' },                                                 pro:{ id:'tm_wall', name:'X-ray' },                           author:{ name:'Blindfold' } },
  'tm-hid-streak':  { clear:{ name:'Through the wall' },                                            pro:{ name:'Sees it coming' },                                author:{ name:'Nothing hidden' } },
  'rx-fl-set':      { clear:{ id:'rx_200', name:'Under 200' },                                      pro:{ name:'Sharp' },                                         author:{ name:'Faster hands' } },
  'rx-fl-streak':   { clear:{ name:'Awake' },                                                       pro:{ id:'rx_run', name:'Steady' },                           author:{ name:'Never late' } },
  'rx-ng-set':      { clear:{ name:'Held back' },                                                   pro:{ id:'rx_clean', name:'Disciplined' },                    author:{ name:'Iron nerve' } },
  'rx-ng-streak':   { clear:{ name:'Patient' },                                                     pro:{ name:'Unshakeable' },                                   author:{ name:'Cold blood' } },
  'sp-ct-set':      { clear:{ name:'Counted' },                                                     pro:{ id:'sp_15', name:'Dead count' },                        author:{ name:'Head start' } },
  'sp-ct-streak':   { clear:{ id:'sp_5', name:'Eight' },                                            pro:{ name:'Keeps count' },                                   author:{ name:'Head count' } },
  'sp-fd-set':      { clear:{ id:'sp_fast', name:'Spotter' },                                       pro:{ id:'sp_clean', name:'No wrong taps' },                  author:{ name:'Eagle' } },
  'sp-fd-streak':   { clear:{ name:'Keeps finding' },                                               pro:{ name:'Never misses' },                                  author:{ name:'Nothing escapes' } },
};
