/* No Excuses — the key's clearance bars (build 22, v14 §9.7 / C.6 / C.7). DATA ONLY (A2).

   One row per contributor combination, keyed '<game>:<mode>:<length>' — the same key progress/key.js builds out of
   GAMES + SET_COPY, so a mode added to config/games.js joins the key with a row here and nowhere else. -1 is Streak.

   A bar is a ONE-OFF threshold, not a score to hold: beat it once in a solo run and that combination is cleared for good
   (9.4 — pass & play and versus never count, L10). `dir` is the direction of that combination's own scoring and is read
   from here, never assumed: 'higher' is a floor (that number or more), 'lower' is a ceiling (that number or less).
   C.7's naming stands — CLEARANCE bar, never "minimum bar" — but its count does not: EIGHT of the thirty are
   ceilings, not nineteen. Estimate, Timing, Reaction and Spot score downward in their SET rows only; their Streak rows
   score rounds survived, which is upward like everything else (L5). The gate checks every row against GC(g,d,s).lower.

   BUILD 44 (FEEDBACK-v24 §E, #371 PORTED): THESE ARE AIDEN'S NUMBERS NOW. Until build 43 every figure here was proposed off
   the build config by Cowork (2026-09-08) and `conf` said how far each sat from evidence. On 2026-09-15 Aiden set 42 of the 90
   by hand on the Key Unlocks Desk: every `bar` (key 1) and the twelve Quick Tap and Dots `pro` figures. They are ported exactly —
   no rounding, no re-derivation, no correction — and carry `conf:'set'`. Three key 1 rows he answered "Fine" (spot:count:-1,
   spot:find:10, spot:find:-1) keep the figure the desk showed, which is a confirmation, not a default.
   Two shapes in his data that any retune must keep: at Pro every Quick Tap and Dots length is the Sprint figure × 1, 3 and 6, and so is
   Dots at key 1; and Quick Tap's Two and Four share ONE key 1 curve — 9 / 26 / 51, just under × 3 and × 6 — but diverge again at Pro
   (13 vs 12), deliberately. The build 44 prompt said × 1 / 3 / 6 for every length; Quick Tap's key 1 is the exception, ported as written.

   THREE TIERS PER ROW SINCE BUILD 32 (v18 B.27). `bar` is key 1 — the clearance bar. `pro` and `author` are keys 2 and 3
   over the SAME combination, in the same unit and direction. A tier whose column has any null is a SHELL — progress/key.js
   derives that from this file, config/keys.js carries no flag — and the key screen says so instead of drawing a ring over
   numbers nobody has set. A column is complete the day every row carries it, and that is the day the tier starts counting.

   A.2 AMENDED AT BUILD 38 (#426, 2026-09-14 — Aiden asked for it directly, and that is what amends it). A build MAY carry a
   PLACEHOLDER, if it is marked as one and is replaceable a row at a time. It may still NEVER set a real bar or silently correct
   one. Each placeholder carries its marker, `placeholder:{ <tier>:{ v, conf:'low', basis } }`, and `v` is the number the marker
   vouches for — so a marker holds only while its cell still says `v`. progress/key.js isPlaceholder() reads it by that test.
   BUILD 44: THE OTHER 48 ARE THE DESK'S PROPOSALS, NOT THE GENERATOR'S. The eighteen Pro figures Aiden had not reached and all
   thirty Author figures were extrapolated on the Key Unlocks Desk from his own numbers (floors about ×1.5, ceilings about ÷1.5,
   the two reaction-time ceilings by subtraction). He accepted the Pro eighteen for play-testing. Each carries its marker with
   `by:'desk'`: isPlaceholder() still reads it as not his number, and site/scripts/placeholders.mjs KEEPS it byte for byte —
   the generator only ever writes an EMPTY cell or a marker of its own (no `by`), so nothing Aiden accepted is regenerated.
   · To put in Aiden's real number: `npm run placeholders -- --set <id> pro|author <n>` writes it and drops that cell's
     marker. Changing the number by hand works too (the marker stops matching and is ignored) — delete the marker as well.
   · From that moment the cell is MANUAL DATA. No later build regenerates it, rounds it, corrects it or re-derives it.
   · `bar` is key 1 and nothing but a person ever writes it.

   BUILD 44 (v24 §D.2, narrowing #435): THIS FILE IS THE SOURCE OF THE KEY ACHIEVEMENT ROSTER. One achievement sits on every
   combination at every tier — 30 × 3 = 90 — named in config/achievements.js KEY_ROSTER and generated by progress/key.js.

   ../_review/key-bars.json is the same table in review shape. The catalogue generator takes its prose from there and its
   NUMBERS out of this file through the running app, and warns when the two disagree — this file is what the game plays. */

export const KEY_BARS = {
  'quick-tap:two:5':      { id:'qt-two-5', bar:9, dir:'higher', pro:13, author:16, unit:'hits', conf:'set', basis:'Aiden’s number: “this first key should be achievable for almost all players” (Key Unlocks Desk, 2026-09-15).',
    placeholder:{ author:{ v:16, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'quick-tap:two:15':     { id:'qt-two-15', bar:26, dir:'higher', pro:39, author:48, unit:'hits', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ author:{ v:48, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'quick-tap:two:30':     { id:'qt-two-30', bar:51, dir:'higher', pro:78, author:96, unit:'hits', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ author:{ v:96, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'quick-tap:four:5':     { id:'qt-four-5', bar:9, dir:'higher', pro:12, author:15, unit:'hits', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 — the same key 1 curve as Two, his 2026-09-13 call that the two modes score alike.',
    placeholder:{ author:{ v:15, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'quick-tap:four:15':    { id:'qt-four-15', bar:26, dir:'higher', pro:36, author:45, unit:'hits', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ author:{ v:45, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'quick-tap:four:30':    { id:'qt-four-30', bar:51, dir:'higher', pro:72, author:90, unit:'hits', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ author:{ v:90, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'dots:blind:5':         { id:'dt-blind-5', bar:7, dir:'higher', pro:11, author:13, unit:'hits', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ author:{ v:13, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'dots:blind:15':        { id:'dt-blind-15', bar:21, dir:'higher', pro:33, author:39, unit:'hits', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ author:{ v:39, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'dots:blind:30':        { id:'dt-blind-30', bar:42, dir:'higher', pro:66, author:78, unit:'hits', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ author:{ v:78, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'dots:lead:5':          { id:'dt-lead-5', bar:9, dir:'higher', pro:15, author:18, unit:'hits', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ author:{ v:18, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'dots:lead:15':         { id:'dt-lead-15', bar:27, dir:'higher', pro:45, author:54, unit:'hits', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ author:{ v:54, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'dots:lead:30':         { id:'dt-lead-30', bar:54, dir:'higher', pro:90, author:108, unit:'hits', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ author:{ v:108, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'hold:grow:7':          { id:'es-grow-set', bar:30, dir:'lower', pro:20, author:13, unit:'% off', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 — far looser than the 9% it replaced, the same correction as his 2026-09-13 call that Estimate was too hard.',
    placeholder:{ pro:{ v:20, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:13, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'hold:grow:-1':         { id:'es-grow-streak', bar:7, dir:'higher', pro:11, author:14, unit:'rounds', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (typed “Round 7”).',
    placeholder:{ pro:{ v:11, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:14, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'hold:cut:10':          { id:'es-cut-set', bar:15, dir:'lower', pro:10, author:7, unit:'% off', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 — the same widening as Grow.',
    placeholder:{ pro:{ v:10, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:7, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'hold:cut:-1':          { id:'es-cut-streak', bar:10, dir:'higher', pro:15, author:19, unit:'rounds', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ pro:{ v:15, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:19, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'sequence:solo:3':      { id:'sq-3', bar:6, dir:'higher', pro:9, author:12, unit:'rounds', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ pro:{ v:9, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:12, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  // v17 (B.9): 'sequence:solo:5' was REMOVED, not retuned — five keys stopped being a combination the config makes
  'sequence:solo:7':      { id:'sq-7', bar:6, dir:'higher', pro:9, author:12, unit:'rounds', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 — the same as 3 keys.',
    placeholder:{ pro:{ v:9, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:12, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  // v18 (B.2): the Set is a TOTAL of five rounds' differences
  'timing:stopwatch:5':   { id:'tm-sw-set', bar:2.5, dir:'lower', pro:1.7, author:1.1, unit:'s total', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ pro:{ v:1.7, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:1.1, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'timing:stopwatch:-1':  { id:'tm-sw-streak', bar:9, dir:'higher', pro:14, author:18, unit:'rounds', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ pro:{ v:14, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:18, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  // v18 (B.4): Hidden is scored in milliseconds off the marker
  'timing:hidden:10':     { id:'tm-hid-set', bar:1500, dir:'lower', pro:1000, author:700, unit:'ms total', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15. He has also asked to adjust this mode’s verdicts (§F.8, waiting on him).',
    placeholder:{ pro:{ v:1000, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:700, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'timing:hidden:-1':     { id:'tm-hid-streak', bar:6, dir:'higher', pro:9, author:12, unit:'rounds', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15. He has also asked to adjust this mode’s parameters (§F.8, waiting on him).',
    placeholder:{ pro:{ v:9, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:12, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'reaction:flash:5':     { id:'rx-fl-set', bar:295, dir:'lower', pro:250, author:220, unit:'ms avg', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ pro:{ v:250, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15 by subtraction from Aiden’s key 1 figure — 295 ÷ 1.5 is 197ms, at or under the human floor for a visual tap. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:220, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15 by subtraction from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'reaction:flash:-1':    { id:'rx-fl-streak', bar:6, dir:'higher', pro:9, author:12, unit:'rounds', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ pro:{ v:9, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:12, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  // v19 (C.5): the Set reads ms OVER the 180ms gate
  'reaction:nogo:5':      { id:'rx-ng-set', bar:400, dir:'lower', pro:320, author:270, unit:'ms avg over 180', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 — slower than a Flash because of the decision.',
    placeholder:{ pro:{ v:320, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15 by subtraction from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:270, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15 by subtraction from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'reaction:nogo:-1':     { id:'rx-ng-streak', bar:10, dir:'higher', pro:15, author:20, unit:'targets', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ pro:{ v:15, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:20, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'spot:count:10':        { id:'sp-ct-set', bar:12, dir:'lower', pro:8, author:5, unit:'miscount', conf:'set', basis:'Aiden’s number, set on the Key Unlocks Desk 2026-09-15 (FEEDBACK-v24 §E).',
    placeholder:{ pro:{ v:8, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:5, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'spot:count:-1':        { id:'sp-ct-streak', bar:8, dir:'higher', pro:12, author:16, unit:'rounds', conf:'set', basis:'Aiden’s number: he kept the figure the desk showed (“Fine”), 2026-09-15.',
    placeholder:{ pro:{ v:12, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:16, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'spot:find:10':         { id:'sp-fd-set', bar:18, dir:'lower', pro:12, author:9, unit:'s total', conf:'set', basis:'Aiden’s number: he kept the figure the desk showed (“Fine”), 2026-09-15.',
    placeholder:{ pro:{ v:12, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:9, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
  'spot:find:-1':         { id:'sp-fd-streak', bar:8, dir:'higher', pro:12, author:16, unit:'rounds', conf:'set', basis:'Aiden’s number: he kept the figure the desk showed (“Fine”), 2026-09-15.',
    placeholder:{ pro:{ v:12, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from Aiden’s key 1 figure. Not Aiden’s number: he accepted it for play-testing and corrects it in play (#371).' },
                  author:{ v:16, conf:'low', by:'desk', basis:'PROPOSED on the Key Unlocks Desk 2026-09-15, extrapolated from the Pro figure. Not Aiden’s number, awaiting his (#371).' } } },
};

// the line under a game's name on the key screen and in the catalogue's clearance-bars section
export const KEY_NOTE = {
  'quick-tap': 'Timed — score is hits. No Set or Streak; the three lengths are the combinations.',
  'dots': 'Timed — score is hits. No lockout between dots, so the ceiling sits above Quick Tap.',
  'hold': 'Set is an average across its rounds. Streak is endless on a 100% cumulative budget, scored in rounds.',
  'sequence': 'One mode, two key counts. Score is rounds. Speed tightens 15ms a round to a 280ms floor.',
  'timing': 'Stopwatch scores seconds off, Hidden milliseconds off the marker (B.4). Both Sets are totals (B.2); both have a Streak.',
  'reaction': 'Flash is a simple reaction; Go / No-go adds the decision — five rounds of three correct taps (B.1b), every tap scored over the 180ms gate (v19 C.5), the Streak in targets on 3000ms (C.6).',
  'spot': 'Count scores total miscount, Find scores total seconds. Both lower is better.',
};
